
development:
  adapter: postgresql
  encoding: unicode
  database: feed_engine_development 
  host: localhost
  pool: 5
  username: deployment
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: feed_engine_test
  host: localhost
  pool: 5
  username: deployment
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: feed_engine
  host: localhost
  pool: 5
  username: deployment
  password: password1
